Receice quests from MG and Knights based on either rank or level
Interkarma/daggerfall-unity pull request #2678
Opened 2024-07-20 20:31 UTC by petchema

In classic Daggerfall, Mages guild and knightly orders can provide quests not only if the player's rank is sufficient, but also if his/her level is sufficient. This PR implements this behavior.

This uses a bit in FactionData's flags, so I think it could be set by mods too.

I provided stubs for mods backward compatibility, even if I don't know if any mod overrides QuestListManager.GetGuildQuest() or QuestListManager.GetGuildQuestPool()

Remark: FACTION.TXT is parsed then cached in FactionData.txt in saves, so you may have to edit or remove FactionData.txt to get updated faction data?

2024-07-20 20:37 UTC, petchema commented on Assets/Scripts/Game/UserInterfaceWindows/DaggerfallWitchesCovenPopupWindow.cs
>              int level = GameManager.Instance.PlayerEntity.Level;     // Not a proper guild so rank = player level
Just noticed that I broke the witches coven, that so far intentionally sent the level as rank parameter.
Either we keep doing that, or add the questByRankOrLevel to them so they enter the PR framework

2024-08-10 23:19 UTC, KABoissonneault requested changes

2024-08-10 23:19 UTC, KABoissonneault commented on Assets/Scripts/API/FactionFile.cs
> +            questByRankOrLevel = 0x100, // Not in classic
Should start with a capital letter

2024-08-10 23:19 UTC, KABoissonneault commented on Assets/StreamingAssets/Factions/FACTION.TXT
> +		flags: 256
Not sure it was necessary to cover the religious knights, but I guess it doesn't hurt

2024-08-13 01:23 UTC, KABoissonneault commented
Change seems good. Was the Coven and Vampire clans from your testing? I can't find info on whether their quests accept level as a rank too, but it also seems under documented

2024-08-13 01:41 UTC, KABoissonneault requested changes
I'm not comfortable with the current "existing save" issue. I feel like if we ship a fix saying quest distribution now works like classic, we're constantly going to get questions from people saying it doesn't work for them.

I think a contingency plan would be to add a new `FactionData_v3` structure (same data as v2), and if a save contains v2 data, add 256 to the flag of the concerned factions. If a save already has v3 data, don't do anything (since mods might want to remove the flags).
Maybe we could also just add a bool to `FactionData_v2`, that's always set to true on save? It would default to false if a save did not have the bool from a previous version, and we can then detect on load if a migration is needed. There's similar code in `SerializablePlayer.RestoreFactionData`

2024-08-15 19:43 UTC, ajrb commented
Hi all, I only found out about this a couple days ago when github emailed me. This was something that I recall discussions about how quests were allocated back in the day but no one ever found that mages & knightly orders behaved differently - I think the assumption was that they were consistent with other guilds who's behaviour was checked - likely the Fighters from my side as that's where I started.

Pechema, I do wish you'd contacted me about this right from the start. I'd have happily worked on a fix for this. It looks like you've used a faction data flag or something for this, but the design in DFU was to not drive the quest offer system off of the flawed Daggerfall faction data - hence the quest list stuff etc. I hate to be that guy after the last month of effort on this PR, but I would like the opportunity to submit an alternative approach that's more aligned with the re-implementation I did for DFU if that would be okay? This will also avoid the faction data change issue for existing saves.

From what I've read here, the change required is just MG and Knight Orders allow quests by rep (as already implemented) or by player level, unless I'm missing something subtle here?

2024-08-15 19:58 UTC, KABoissonneault commented
Allegedly, the fix should cover vampire clans and witch covens too. I'm not sure where this has been verified

2024-08-15 20:03 UTC, ajrb commented
That would complicate things a little since they're not actually proper 'guilds', can anyone verify thatin vanilla? I don't have any saves that would enable doing that quickly.

2024-08-15 22:36 UTC, petchema commented
@ajrb This is an idea I experimented with after seeing a streamer (Grimith I guess) being offered by classic DF two rank 7 knight quests right after joining the order, so there was an obvious discrepancy with what DFU currently does.

 I have no issue with another implementation replacing this one at all, that's something I tried for myself on a subsystem I don't know well, so I'm sure I did plenty of things wrong ;)

2024-08-16 20:44 UTC, ajrb commented
@petchema Thanks, will submit my alternate proposed solution soon. I noticed that UESP now correctly states this for MG & Knights pages. I'm fairly sure that wasn't the case back in March 2018 when I wrote the quest list code originally, but maybe I was just not dilligent enough back then. :)

Did you have some evidence for this behaviour also being used for Vampire Clan and Witch Covern quest dispensing that KAB mentioned? 
It doesn't make sense to me for Vampire quest as they are dispensed by delivered letters once the player has joined the vamps, rank or level is not relevant. 
For witches coverns, UESP states reputation is how quests are selected. It would be easy enough to change if someone does provide evidence from classic.

2024-08-16 22:15 UTC, closed without merging

2024-08-16 22:15 UTC, petchema commented
Obsoleted by #2688